# This workflow is triggered on push to the main branch and on pull request events.
name: Enforce Coding Styling For Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      # don't run this workflow when the are pushes, and there are only changes for this directories:
      - ".github/**"
      - "minutes/**"
      - "presentations/**"
      - "reports/**"
      # don't run this workflow when the are pushes and there are only changes for the following files:
      - "**.md"
      - "**.gitignore"

  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      # don't run this workflow when the are pushes, and there are only changes for this directories:
      - ".github/**"
      - "minutes/**"
      - "presentations/**"
      - "reports/**"
      # don't run this workflow when the are pushes and there are only changes for the following files:
      - "**.md"
      - "**.gitignore"

jobs:
  test-eslint:
    name: Test ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./ChargeHub/frontend/ChargeHub
        run: npm install

      - name: Run ESLint with Airbnb config
        working-directory: ./ChargeHub/frontend/ChargeHub
        run: npm run lint