on:
  workflow_run:
    workflows:
      ["Run Selenium Tests with Chrome", "CI with Maven and SonarCloud"]
    branches: [main]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy ChargeHub
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Write .env file
        working-directory: ./ChargeHub
        run: |
          cat <<EOF > .env
          MYSQL_PASSWORD=admin
          MYSQL_USER=admin
          MYSQLDB_USER=admin
          MYSQLDB_ROOT_PASSWORD=admin
          MYSQLDB_DATABASE=tqs_db
          MYSQLDB_PASSWORD=admin
          MYSQLDB_LOCAL_PORT=33060
          MYSQLDB_DOCKER_PORT=3306
          SPRING_LOCAL_PORT=8080
          SPRING_DOCKER_PORT=8080
          GRAFANA_ADMIN=admin
          GRAFANA_PASSWORD=admin
          EOF

      - name: Write test application.properties
        run: |
          mkdir -p ./ChargeHub/backend/src/test/resources
          cat <<EOF > ./ChargeHub/backend/src/test/resources/application.properties
          spring.application.name=backend
          management.endpoint.health.show-details=always
          management.endpoint.health.access=unrestricted
          management.endpoints.web.exposure.include=health,info,metrics,prometheus
          management.endpoint.prometheus.show-details=always
          management.endpoint.info.access=unrestricted
          management.endpoint.info.show-details=always
          management.endpoint.metrics.access=unrestricted
          management.endpoint.metrics.show-details=always
          management.endpoint.prometheus.enabled=true
          management.metrics.export.prometheus.enabled=true
          springdoc.swagger-ui.path=/swagger-ui-custom.html
          springdoc.api-docs.path=/api-docs
          jwt.secret=wBv3slbZ4PQNZQkRjrUQv9UVUKbLn7b/JchYmVK55LWVfFCkN2o1C0k9qigXHZCU4grZ7lj04qXw9Sx56Zay4ZQio8huHSHO8hdkusSHUsuu8232
          spring.flyway.enabled=true
          spring.flyway.locations=classpath:db/migration
          stripe.api-key=${{ secrets.STRIPE_API }}
          EOF

      - name: Write main application.properties
        run: |
          mkdir -p ./ChargeHub/backend/src/main/resources
          cat <<EOF > ./ChargeHub/backend/src/main/resources/application.properties
          spring.application.name=backend
          management.endpoint.health.show-details=always
          management.endpoint.health.access=unrestricted
          management.endpoints.web.exposure.include=health,info,metrics,prometheus
          management.endpoint.prometheus.show-details=always
          management.endpoint.info.access=unrestricted
          management.endpoint.info.show-details=always
          management.endpoint.metrics.access=unrestricted
          management.endpoint.metrics.show-details=always
          management.endpoint.prometheus.enabled=true
          management.metrics.export.prometheus.enabled=true
          springdoc.swagger-ui.path=/swagger-ui-custom.html
          springdoc.api-docs.path=/api-docs
          jwt.secret=wBv3slbZ4PQNZQkRjrUQv9UVUKbLn7b/JchYmVK55LWVfFCkN2o1C0k9qigXHZCU4grZ7lj04qXw9Sx56Zay4ZQio8huHSHO8hdkusSHUsuu8232
          spring.flyway.enabled=true
          spring.flyway.locations=classpath:db/migration
          stripe.api-key=${{ secrets.STRIPE_API }}
          EOF

      - name: Down containers
        working-directory: ./ChargeHub
        run: docker compose down -v --remove-orphans

      - name: Remove build caches
        working-directory: ./ChargeHub
        run: docker builder prune -a -f

      - name: Package backend
        working-directory: ./ChargeHub/backend
        run: mvn clean package -DskipTests

      - name: Build and up containers
        working-directory: ./ChargeHub
        run: docker compose -f docker-compose.prod.yaml up --build -d
